### ISSUE TITLE
Is the list of servers just the seed or do you have to list every replica set member?

### ISSUE THREAD

**Issue by travischoma** [diversario/connect-mongostore#11]
In a typical mongo connection string one only needs to list a couple servers as seed, and the full replica set configuration is discovered. 

Specifically mongohq gives you a recommended connection string with 2 servers, but the replication set that's configured has 1 master, 2 primary and an arbiter.

If I set the server array property in the connect-mongostore config object to list the two servers in the monghq connection string, does it discover the full replication set since it's built on top of the mongo driver?

**Comment by travischoma** [comment]
The way I read it is, I'd add the 2 servers from the connection string, but then specify replicationOptions: { rs_name: 'setName' } properties for each server. Is that correct?

**Comment by travischoma** [comment]
er I mean set the replicaSetOption once on the db connection. I think I answered my own question.

**Comment by diversario** [comment]
Well, that was easy!
