### ISSUE TITLE
The readme mentions a callback as 2nd param but there is no callback made

### ISSUE THREAD

**Issue by travischoma** [diversario/connect-mongostore#12]
If I use MongoStore(opts,cb) the cb is never called. Doesn't look like there is code to trigger the callback.

**Comment by diversario** [comment]
Right. The text is from when `Db#open` was called immediately in the constructor; I removed that in favor of doing lazy `open`. Database is going to be `open`ed when `set`, `get`, `destroy`, `length` or `clear` is called. I'll update the README.

**Comment by travischoma** [comment]
fwiw I forked it to do the open in the constructor again. Needed to get a callback when it was properly connected to my repl set before proceeding with the rest of the express configuration, the lazy loading was causing this error on the first request of my app after server restart: Error setting TTL index on collection :  <Error: Error setting TTL index on collection : <Error: No replica set primary available for query with ReadPreference PRIMARY>> type errors when the web app launched before it was fully connected.
