### ISSUE TITLE
SSL doesn't seem to work with replica sets

### ISSUE THREAD

**Issue by donnguyen-dev** [diversario/connect-mongostore#22]
The ssl:true option does not appear to work with replica sets. Is this a bug or is there a special/different configuration option that should be used when a replica set configuration is required?

**Comment by syzer** [comment]
+1
have a look
https://github.com/kcbanner/connect-mongo/pull/25/files

**Comment by diversario** [comment]
Sorry for not getting to this sooner. You can add `ssl` option to each individual server configuration you're passing to the module, that should work.
