### ISSUE TITLE
Existing mongoose replica set connection

### ISSUE THREAD

**Issue by bcomerford** [diversario/connect-mongostore#23]
I'm using a MongoHQ(Compose) replica set and am having issues using that existing mongoose connection with the mongostore, is there additional configuration I'm missing?

**Comment by diversario** [comment]
Can you elaborate on what sort of issues you're having?

**Comment by bcomerford** [comment]
I create the mongostore with existing mongoose
var db = mongoose.connect('mongodb://<user>:<password>@host:port,host:port/db')
var sessionStore = new mongoStore({ mongooseConnection : app.db.connections[0] });
app.use(express.session({
  store: sessionStore
}));

returns:
Error: host must be specified [undefined]
which I believe is because the existing mongoose connection has an array of "hosts" rather than a single "host" that mongostore is looking for.

**Comment by diversario** [comment]
Makes sense. I'll try to fix this ASAP.

**Comment by diversario** [comment]
What's your version of Mongoose?

**Comment by diversario** [comment]
Can you try v0.1.4? It's in npm.

**Comment by bcomerford** [comment]
That did it!

**Comment by diversario** [comment]
:+1:
