### ISSUE TITLE
Question on expiring sessions from a particular API call

### ISSUE THREAD

**Issue by rickwaugh1** [diversario/connect-mongostore#5]
We are running on Amazon. The load balancer sends a test to the servers every 15 seconds to make sure the app is alive. We have coded an API call for it to check, which tests if both node and mongo are working. However, this creates a session, with each call, as it's not a web browser, so a new session gets built. We have 80,000 records in our session database, that expire every four weeks. Wondering if there is any way to prevent this happening.

**Comment by diversario** [comment]
Have you figured something out about this? I'm trying to think of a good solution. Off the top of my head I imagine you could destroy the session in your route handler so it's removed from the db.

**Comment by rickwaugh1** [comment]
What we ended up doing was set up a route for the load balancer test 
call before the session info set up. So, instead of expiring the 
session, the session never happens. Works well.

On 2014-04-07 7:35 PM, Ilya Shaisultanov wrote:

> Have you figured something out about this? I'm trying to think of a 
> good solution. Off the top of my head I imagine you could destroy the 
> session in your route handler so it's removed from the db.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/diversario/connect-mongostore/issues/5#issuecomment-39806134.

## 

Server Developer
Finger Food Studios Inc.
tel: 604-475-0350
email: rick@fingerfoodstudios.com

skype: rick.waugh4

www.fingerfoodstudios.com

MESSAGES / COMMENTS This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately and return the original message to us at the above address. Thank you.

**Comment by diversario** [comment]
That's a great solution!
