### ISSUE TITLE
Fix for Express 4.0

### ISSUE THREAD

**Issue by outrightmental** [diversario/connect-mongostore#9]
When upgrading to Express 4.0, **connect-mongostore** experiences the issue identical  issue as **connect-mongo** detailed [here](https://github.com/kcbanner/connect-mongo/issues/103) and [here](https://github.com/kcbanner/connect-mongo/issues/109).

However, I notice this issue has been fixed on Github, in version 0.1.  However the most recent version published to NPM is 0.0.13.  What's the status?

**Comment by diversario** [comment]
Apparently, I forgot to publish it, my fault.
Published.

**Comment by outrightmental** [comment]
@diversario THANK YOU
